### ISSUE TITLE
running very slowly

### ISSUE THREAD

**Issue by idol999** [hcd233/fine-tuning-Bert-for-sentiment-analysis#2]
Why are inference.py running very slowly? I tested it on colab and already trained the model.

**Comment by hcd233** [comment]
I think you may want to use inference.py to infer a batch of sentences. Could you provide more details of your work on inference?

**Comment by idol999** [comment]
> I think you may want to use inference.py to infer a batch of sentences. Could you provide more details of your work on inference?


<img width="1015" alt="image" src="https://user-images.githubusercontent.com/78726524/236622095-f28c6d8f-adab-4e2b-8548-624cdd8d2fca.png">

I don't think I made myself clear. The problem I encountered is shown in the figure above, with no output after running the program.

**Comment by idol999** [comment]
> I think you may want to use inference.py to infer a batch of sentences. Could you provide more details of your work on inference?

I have solved the problem.In inference.py ，we need to import numpy and pandas before import transformers.These two modules are usually required when using transformers modules.
Thanks your great work.

**Comment by hcd233** [comment]
Fine. Thanks for your nice Issue. :)
